### ISSUE TITLE
Beads of Ruin

### ISSUE THREAD

**Issue by nterrien** [DhSufi/PokemonTeamListCreator#2]
If i have a pokémon with Beads of Ruin in my team the pdf convert it to Vessel of Ruin. It is the same if the language is French or Italian (and maybe other languages)

Input:
```
Chi-Yu @ Choice Specs  
Ability: Beads of Ruin  
Tera Type: Ghost  
EVs: 4 HP / 252 SpA / 252 Spe  
Timid Nature  
- Heat Wave  
- Snarl  
- Overheat  
- Dark Pulse  
```
Output:
[output.pdf](https://github.com/DhSufi/PokemonTeamListCreator/files/14151541/-staff.pdf)

**Comment by nterrien** [comment]
I found in the file Resources/Abilities/TranslatorAbilities.js line 22
```    "Beads of Ruin": "284",```
i think it should be 
```    "Beads of Ruin": "287",```

**Comment by DhSufi** [comment]
Thank you so much!! I am so sorry for that. I appreciate a lot your time for fixing it.
